### ISSUE TITLE
ImgurClientError(response_data['data']['error'], response.status_code) imgurpython.helpers.error.ImgurClientError: (404) Unable to find an album with the id, Q1s4N

### ISSUE THREAD

**Issue by chipweinberger** [makuto/redditLikedSavedImageDownloader#10]

**Comment by chipweinberger** [comment]
Traceback (most recent call last):
  File "redditUserImageScraper.py", line 200, in <module>
    main()
  File "redditUserImageScraper.py", line 188, in main
    only_important_messages = settings['Only_important_messages'])
  File "/Users/chip/Downloads/redditLikedSavedImageDownloader-master/imageSaver.py", line 462, in saveAllImages
    soft_retrieve_imgs = soft_retrieve_imgs)
  File "/Users/chip/Downloads/redditLikedSavedImageDownloader-master/imageSaver.py", line 283, in saveAllImgurAlbums
    albumImages = imgurClient.get_album_images(albumId)
  File "/Library/Python/2.7/site-packages/imgurpython/client.py", line 283, in get_album_images
    images = self.make_request('GET', 'album/%s/images' % album_id)
  File "/Library/Python/2.7/site-packages/imgurpython/client.py", line 161, in make_request
    raise ImgurClientError(response_data['data']['error'], response.status_code)
imgurpython.helpers.error.ImgurClientError: (404) Unable to find an album with the id, Q1s4N.

**Comment by chipweinberger** [comment]
Thanks for you work in making this.

**Comment by makuto** [comment]
I'm afk right now (using phone), so it'll be a couple hours until I can
help you. Looks like I need to handle exceptions from the imgur API calls.
I'll let you know once I patch it.

In the meantime you can enable Use_Cached_Submissions then set a skip
percent that is past the problematic album (e.g. if it fails at 34% set
skip percent to 35%). Both of these settings are in settings.txt.

You'll want to set these back to their previous values once you're done.
I'm also not 100% sure it'll skip percent in imgur albums, so this
workaround might not work.

**Comment by makuto** [comment]
c5d4f78a893c1154e4e122d836c9158eadae5700 should fix your issue. You might want to manually visit that album to see what's the matter with it.

**Comment by chipweinberger** [comment]
Wow thank you! Will give it a shot.
