### ISSUE TITLE
EOFError

### ISSUE THREAD

**Issue by jonathanlaniado** [makuto/redditLikedSavedImageDownloader#14]
After choosing my settings, I get this error on repeat in the output:

`ERROR:tornado.application:Exception in callback <function updateScriptStatus at 0x7f9cade0ab90>
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tornado/ioloop.py", line 1229, in _run
    return self.callback()
  File "LikedSavedDownloaderServer.py", line 435, in updateScriptStatus
    pipeOutput = scriptPipeConnection.recv()
EOFError`

I've tried Python 2 and Python 3, too.

**Comment by makuto** [comment]
What operating system are you using?

**Comment by makuto** [comment]
Give 4b6b2a8 a try. I'm not 100% sure it will fix your issue.

**Comment by makuto** [comment]
Closing due to inactivity
