### ISSUE TITLE
Removed (gif) imgur links throwing errors

### ISSUE THREAD

**Issue by den747** [makuto/redditLikedSavedImageDownloader#15]
Hi, there seems to be a problem with removed imgur (gif) links.

```
Url "https://i.imgur.com/7ra1BbN.gifv" has a suspicious number of lines (6)   
Traceback (most recent call last):   
  File "redditUserImageScraper.py", line 131, in <module>
    runLikedSavedDownloader(None)
  File "redditUserImageScraper.py", line 115, in runLikedSavedDownloader
    only_important_messages = settings.settings['Only_important_messages'])
  File "/data/redditLikedSavedImageDownloader/imageSaver.py", line 408, in saveAllImages
    url = convertGifVUrlToWebM(url)
  File "/data/redditLikedSavedImageDownloader/imageSaver.py", line 155, in convertGifVUrlToWebM
    gifvSource = findSourceFromHTML(url, GIFV_SOURCE_KEY)
  File "/data/redditLikedSavedImageDownloader/imageSaver.py", line 106, in findSourceFromHTML
    foundSourcePosition = lineStr.lower().find(sourceKey.lower())
TypeError: argument should be integer or bytes-like object, not 'str'
```

Greetings

**Comment by makuto** [comment]
These should now be handled gracefully with 6ea8d80.
