### ISSUE TITLE
Ascii Encoding

### ISSUE THREAD

**Issue by tankoks** [makuto/redditLikedSavedImageDownloader#5]
I get this error. Line Numbers may be off by 3 or so since i tried to change the encoding.

Traceback (most recent call last):
  File "redditUserImageScraper.py", line 150, in <module>
    main()
  File "redditUserImageScraper.py", line 129, in main
    only_important_messages = settings['Only_important_messages'])
  File "~/REDDITRIP/redditLikedSavedImageDownloader-master/imageSaver.py", line 401, in saveAllImages_Advanced
    if os.path.isfile(saveFilePath):
  File "/usr/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 29-30: ordinal not in range(128)

Also I have a suggestions. Can all the not supported links be printed in a text file?

**Comment by makuto** [comment]
Oops, looks like I need to make sure to parse out the Unicode there.

That's a good idea, I'll add that.
I was planning on having the script output all the posts in JSON or XML
too, but I kept hitting Unicode problems. I can give it another go if
desired.

On Jan 11, 2017 9:29 PM, "tankoks" <notifications@github.com> wrote:

I get this error

Traceback (most recent call last):
File "redditUserImageScraper.py", line 150, in
main()
File "redditUserImageScraper.py", line 129, in main
only_important_messages = settings['Only_important_messages'])
File "/home/seedbox/shares/AV/REDDITRIP/redditLikedSavedImageDownloader-master/imageSaver.py",
line 401, in saveAllImages_Advanced
if os.path.isfile(saveFilePath):
File "/usr/lib/python2.7/genericpath.py", line 37, in isfile
st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode characters in position
29-30: ordinal not in range(128)

Also I have a suggestions. Can all the not supported links be printed in a
text file?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/makuto/redditLikedSavedImageDownloader/issues/5>, or mute
the thread

**Comment by makuto** [comment]
Could you get latest and try uncommenting imageSaver.py:282 and imageSaver.py:409? (remove the '#' from the front of the line, in case you don't know)

I added that line which makes sure that file paths should be alphanumeric only. I personally don't have any problems without it, but maybe you have a weird directory or submission title where it's breaking.

I added that code and writing out Unsupported Submissions to .json in 26b3f6e146313e668193354479fd806afdfc7149 . You'll find the UnsupportedSubmissions.json file in your output_dir.

**Comment by tankoks** [comment]
I started getting a different error. Not sure whats causing this. Maybe a broken saved link?

Traceback (most recent call last):
  File "redditUserImageScraper.py", line 156, in <module>
    main()
  File "redditUserImageScraper.py", line 134, in main
    only_important_messages = settings['Only_important_messages'])
  File "/home/user/scripts/redditLikedSavedImageDownloader/imageSaver.py", line 382, in saveAllImages_Advanced
    urlContentType = getUrlContentType(url)
  File "/home/user/scripts/redditLikedSavedImageDownloader/imageSaver.py", line 33, in getUrlContentType
    openedUrl = urllib.urlopen(url)
  File "/usr/lib/python2.7/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 350, in open_http
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno -2] Name or service not known

**Comment by makuto** [comment]
Could you add the following line to imageSaver.py `getUrlContentType()`, between lines 32 and 33 (indent to the same indentation as line 33):
`print url`
That will print every url that gets put through that function. It should print out the URL you're getting stuck on right before you get that same Traceback. If you can send me the URL it prints I can add a filter to make sure it won't get tripped up.

**Comment by tankoks** [comment]
It failed at a dead link that ended with a file name (e.g. www.deadwebsite.com/deadimage.jpeg).

Also when uncommenting the unicode bits, the files would be saved as ______jpg instead of _____ .jpg. I changed line 378 to saveFilePath = safeFileName(saveFilePath, file_path = True) + u'.' + fileType and that fixes the extension but unless you change the previous line too it saves as _____jpg.jpg

I indented 349 to 405 and added a try/except and that seems to stop the script from breaking.

**Comment by makuto** [comment]
I added exception handling in d95b0ff39528772f6981ebff59738fe595d5a5d6 which should hopefully resolve your issues. If not, open up another issue with the full Traceback.

Note that I updated settings.txt, so when you fetch you might have to merge conflicts. It's harmless if you ignore all changes to that file (keeping your settings) as well.

Thanks, and I hope you enjoy using the script!
